trigger:
  - main

pool:
  name: agentPool   # usa o agente self-hosted MacM4-Agent

steps:
  # Checkout do repositório
  - checkout: self

  # Instalar JDK 17 no agente
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Configurar cache para Gradle
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | build.gradle'
      restoreKeys: |
        gradle | "$(Agent.OS)"
      path: ~/.gradle
    displayName: 'Cache Gradle dependencies'

  # Rodar build com Gradle Wrapper
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build'
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'       # Agora deve funcionar
      jdkArchitectureOption: 'x64'

  # Publicar resultados de testes
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'JUnit Tests'
