# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: agentPool

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'   # Caminho para o Gradle Wrapper
      tasks: 'build'                 # Altere se quiser rodar outras tasks (ex: test)
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'   # Informa que vamos usar versão do JDK instalada no agente
      jdkVersionOption: '1.17'       # Java 21
      jdkArchitectureOption: 'x64'
