spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

server:
  port: ${SERVER_PORT}
